### ISSUE TITLE
Issue Using Https

### ISSUE THREAD

**Issue by dannykitchen** [sky-uk/terraform-provider-infoblox#64]
Have an issue on apply when using https, can you advise please ?

Post https://XXXXX/wapi/v2.6.1/record:cname: x509: certificate signed by unknown authority

**Comment by dannykitchen** [comment]
Also getting on my applicance
Version 2.6.1 not supported
Where would be the best place to downgrade this ?

**Comment by ruimoreira** [comment]
as for the ssl error you can export the following env variable 

INFOBLOX_ALLOW_UNVERIFIED_SSL = true 

or place that inside provider.tf if you are defining the variables there.

As for the api version we are currently working on this issue aiming to allow  the user to specify the version of the api to use.

**Comment by dannykitchen** [comment]
Thanks, that now giving another error when pipe in as per below 

    INFOBLOX_ALLOW_UNVERIFIED_SSL = "${var.INFOBLOX_ALLOW_UNVERIFIED_SSL}"

1 error(s) occurred:

* provider.infoblox: : invalid or unknown key: INFOBLOX_ALLOW_UNVERIFIED_SSL

**Comment by dannykitchen** [comment]
Many thanks, where can i change the version type in the go files to recompile with our current version please ?

**Comment by ruimoreira** [comment]
As for the ssl setting , if you are setting it in a .tf file , it needs to be lower case 

allow_unverified_ssl 

Sorry if I have confused you.

As for manually changing the api version, I would advise against doing this, because the data model that we have might not apply to the version you are trying to use, this said we expect to add support for multiple api versions soon. If you still wish to do this you can have a look inside terraform-provider-infoblox/vendor/github.com/sky-uk/skyinfoblox/api/ you will find there are several directories each of them represents a resource. Inside you will find a file called <resourcename>_model.go , there should be a constant there that defines the version of the api.
Again I would advise you against doing this as we are expecting to change the way we support different api versions soon.

kind regards 

Rui

**Comment by dannykitchen** [comment]
Thanks Rui, i just need to run a proof of concept using CNAMES to begin with, so will give this ago.

Many thanks again
